export default {
  label: 'Human Body',
  id: 'human-body-2',
  lockAfter: 4,
  list: [
    {
      label: 'Digestive System - Reading',
      type: 'passage',
      id: 'passage',
      data: {
        title: 'Digestive System',
        text: `We need energy to do our daily activities. We get energy from the food we eat. If we don't take food for some time, we will feel hungry. 
  A group of our body parts work together and convert the food we eat into fuel that body needs to function. While eating we first chew the food in our mouth. Saliva present in our mouth helps in breaking the food into small pieces. Your tongue does the work of pushing the food around, and your teeth will do the work of chewing. The food will be made into a soft moist ball which is easy to swallow.
  The esophagus is like a flexible pipe and it takes the food from mouth to stomach. Stomach is the place where digestion happens. Acidic fluids present in stomach helps in breaking down the food further. Energy present in our food, is absorbed from the walls of stomach and passed through blood stream. 
  Then the food is passed to small intestine. Bile is a digestive juice helps in breaking down the fats when the food passes through small intestine. Bile is created in liver, which is the largest human organ. 
  After extracting fats and other nutrients, the waste is passed to large intestine, and finally reaches rectum. 
  All the body parts we discussed above, together form the digestive system. It is an important function of our body. Always eat healthy food even if they are less tasty, so that your digestive system will be happy.`
      }
    },
    {
      label: 'Digestive System - Parts',
      type: 'dragAndDrop',
      id: 'dnd',
      data: {
        img: 'digestive.jpg',
        title:
          'Drag and drop the parts of digestive sytem at appropriate places.',
        width: 310,
        height: 380,
        wordWidth: 100,
        words: [
          {
            word: 'esophagus',
            x: 190,
            y: 90
          },
          {
            word: 'stomach',
            x: 215,
            y: 186
          },
          {
            word: 'liver',
            x: 100,
            y: 210
          },
          {
            word: 'small intestine',
            x: 0,
            y: 310
          },
          {
            word: 'large intestine',
            x: 220,
            y: 280
          },
          {
            word: 'rectum',
            x: 190,
            y: 350
          }
        ]
      }
    },
    {
      label: 'Digestive System - MCQ',
      type: 'mcq',
      id: 'mcq',
      data: {
        title: 'Multiple Choice Question',
        questions: [
          {
            qText:
              "If we don't take food for a long time, we will feel ________",
            options: 'hungry, sleepy, angry, boring'
          },
          {
            qText: 'Which is the biggest organ in our body?',
            options: 'Liver, Lungs, Heart, Kidney'
          },
          {
            qText: 'Bile helps in breaking ______.',
            options: 'Fat, Glucose, Protein'
          },
          {
            qText: 'What is the final destination of the food we eat?',
            options: 'rectum, large intestine, small intestine, stomach'
          },
          {
            qText: 'What is the digestive juice generated by Liver.',
            options: 'Bile, Enzyme, Acidic acid'
          }
        ]
      }
    },
    {
      label: 'Brain - Reading',
      type: 'passage',
      id: 'passage-2',
      data: {
        title: 'The Brain',
        text: `Brain is the decision maker of our body. It controls all the movements of the body. It is responsible for human intelligence, memory and imagination. 
  Brain is the most important organ for us. That is why, we should wear a helmet when you ride a two wheeler. 
  # Structure of the Human brain. 
  The brain is kept in a bony case called Skull. Skull is made up of eight immovable bones. The brain is protected by three membranes called meninges. The brain is made up of tiny nerve cells called neurons. The brain is the centre of the nervous system. 
  The brain is made up of three parts. 
  1. Cerebrum 
  2. Cerebellum 
  3. Medulla oblongata 
  # Cerebrum 
  1. It is the largest part of the brain. 
  2. It is responsible for our memory. 
  3. We are able to learn languages, understand signs and symbols with the help of cerebrum. 
  4. The right side of the Cerebrum controls the left side of our body and vice versa. 
  5. Cerebrum is responsible for intelligence, imagination and reasoning. 
  # Cerebellum 
  1. It co-ordinates the movements of the muscles of our body. 
  2. It helps to maintain the balance of the body. 
  # Medulla oblongata 
  1. It is also called the brain stem. 
  2. It controls the breathing, heart beat and other involuntary muscles. 
  3. It connects the brain to the spinal cord.`
      }
    },
    {
      label: 'Parts of Brain - Practice',
      type: 'dragAndDrop',
      id: 'dnd-2',
      data: {
        img: 'brain.jpg',
        title: 'Drag and drop the parts of the brain at appropriate places.',
        width: 271,
        height: 368,
        wordWidth: 120,
        words: [
          {
            word: 'Cerebrum',
            x: 20,
            y: 10
          },
          {
            word: 'Medulla oblongata',
            x: 125,
            y: 270
          },
          {
            word: 'Cerebellum',
            x: 10,
            y: 310
          }
        ]
      }
    },
    {
      label: 'Brain - MCQ',
      type: 'mcq',
      id: 'mcq-2',
      data: {
        title: 'Multiple Choice Question',
        questions: [
          {
            qText: 'What is the largest part of the brain?',
            options: 'Cerebrum, Cerebellum, Medulla oblongata'
          },
          {
            qText: 'Brain is protected by ________.',
            options: 'skull, hair, neurons, spinal cord'
          },
          {
            qText: 'Which part of the brain controls the movement of muscles?',
            options: 'Cerebellum, Medulla oblongata, Cerebrum'
          },
          {
            qText: 'Which part of the brain controls heart beat?',
            options: 'Medulla oblongata, Cerebrum, Cerebellum'
          },
          {
            qText:
              'Which part of the brain connects the brain to the spinal cord?',
            options: 'Medulla oblongata, Cerebrum, Cerebellum'
          },
          {
            qText: 'Medulla oblongata is also known as _________.',
            options: 'brain stem, neck, root of brain'
          },
          {
            qText: 'The brain is made up of tiny nerve cells called _______.',
            options: 'neurons, meninges, nerves'
          },
          {
            qText: 'Which part of the brain helps in learning a language?',
            options: 'Cerebrum, Cerebellum, Medulla oblongata'
          }
        ]
      }
    }
  ]
};
